name: Wallabag Link Checker
description: Checks Wallabag bookmarks for dead links and tags them with "dead"
author: Frank Kloeker
inputs:
  WALLABAG_URL:
    description: Wallabag instance URL
    required: true
  WALLABAG_CLIENT_ID:
    required: true
  WALLABAG_CLIENT_SECRET:
    required: true
  WALLABAG_USERNAME:
    required: true
  WALLABAG_PASSWORD:
    required: true
  WALLABAG_API_TIMEOUT:
    required: false
  HTTP_CHECK_TIMEOUT:
    required: false
  TLS_HANDSHAKE_TIMEOUT:
    required: false
runs:
  using: docker
  image: docker://ghcr.io/eumel8/wallabag-checklinks/wallabag-checklinks:0.0.8
branding:
  icon: link
  color: blue
